version: 2
jobs:
  build:
    docker:
      - image: cyph/circleci:latest
    working_directory: /cyph
    steps:
      - checkout
      - run: |
          export circleCI=true
          source ~/.bashrc
          /cyph/commands/build.sh
